server:
  port: ${PORT:8761}

spring:
  application:
    name: registry

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
