server:
  port: ${PORT:8761}

spring:
  application:
    name: registry

eureka:
  server:
    UseReadOnlyResponseCache: false
  instance:
    ip-address: ${IP_ADDRESS:172.30.40.220}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
