version: '3.7'

services:

  microservices-registry:
    container_name: microservices-registry
    build:
      context: ./microservices-registry
      dockerfile: prod.Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 300m
    restart: always
    env_file:
      - .env

  microservices-configuration:
    container_name: microservices-configuration
    build:
      context: ./microservices-configuration
      dockerfile: prod.Dockerfile
    volumes:
      - $HOST_CONFIG_LOCATION:$CONFIG_LOCATION
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 300m
    restart: always
    depends_on:
      - microservices-registry
    env_file:
      - .env

  microservices-gateway:
    container_name: microservices-gateway
    build:
      context: ./microservices-gateway
      dockerfile: prod.Dockerfile
    network_mode: "host"
    volumes:
      - /etc/timezone:/etc/timezone
    deploy:
      resources:
        limits:
          memory: 500m
    restart: always
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env

  microservices-account:
    container_name: microservices-account
    build:
      context: ./microservices-account
      dockerfile: prod.Dockerfile
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env

  microservices-todo:
    container_name: microservices-todo
    build:
      context: ./microservices-todo
      dockerfile: prod.Dockerfile
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env
