version: '3.7'
services:

  microservices-registry:
    build:
      context: ./microservices-registry
      dockerfile: prod.Dockerfile
    network_mode: "host"

  microservices-configuration:
    build:
      context: ./microservices-configuration
      dockerfile: prod.Dockerfile
    network_mode: "host"
    volumes:
      - $PWD/target/configurations:/home/sbx0/configurations
    depends_on:
      microservices-registry:
        condition: service_healthy
    environment:
      PASSWORD:
      CONFIG_LOCATION:

  microservices-gateway:
    build:
      context: ./microservices-gateway
      dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy
    environment:
      PASSWORD:
      CONFIG_LOCATION:

  microservices-account:
    build:
      context: ./microservices-account
      dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy
    environment:
      PASSWORD:
      CONFIG_LOCATION:

  microservices-uno:
    build:
      context: ./microservices-uno
      dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy
    environment:
      PASSWORD:
      CONFIG_LOCATION:
