version: '3.7'
services:

  microservices-registry:
    build: ./microservices-registry
    dockerfile: prod.Dockerfile
    network_mode: "host"

  microservices-configuration:
    build: ./microservices-configuration
    dockerfile: prod.Dockerfile
    network_mode: "host"
    volumes:
      - /home/sbx0/configurations:/home/sbx0/configurations
    depends_on:
      microservices-registry:
        condition: service_healthy

  microservices-gateway:
    build: ./microservices-gateway
    dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy

  microservices-account:
    build: ./microservices-account
    dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy
      microservices-gateway:
        condition: service_healthy

  microservices-uno:
    build: ./microservices-uno
    dockerfile: prod.Dockerfile
    network_mode: "host"
    depends_on:
      microservices-configuration:
        condition: service_healthy
      microservices-registry:
        condition: service_healthy
      microservices-gateway:
        condition: service_healthy