version: '3.7'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --authentication_policy=*
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
    environment:
      MYSQL_ROOT_PASSWORD: test
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass test
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 300m

  microservices-registry:
    container_name: microservices-registry
    build:
      context: ./microservices-registry
      dockerfile: Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 300m
    restart: always
    env_file:
      - .env

  microservices-configuration:
    container_name: microservices-configuration
    build:
      context: ./microservices-configuration
      dockerfile: Dockerfile
    volumes:
      - $HOST_CONFIG_LOCATION:$CONFIG_LOCATION
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 300m
    restart: always
    depends_on:
      - microservices-registry
    env_file:
      - .env

  #  microservices-gateway:
  #    build:
  #      context: ./microservices-gateway
  #      dockerfile: Dockerfile
  #    depends_on:
  #      microservices-configuration:
  #        condition: service_healthy
  #      microservices-registry:
  #        condition: service_healthy
  #    network_mode: "host"
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 300m
  #    environment:
  #      REGION:
  #      VERSION:
  #      REGISTRY_URL:
  #      SECURITY_NAME:
  #      SECURITY_PASSWORD:
  #      CONFIG_URL:
  #      HOST_CONFIG_LOCATION:
  #      CONFIG_LOCATION:
  #      REDIS_HOST:
  #      REDIS_PORT:
  #      REDIS_PASSWORD:
  #      DB_URL:
  #      DB_USERNAME:
  #      DB_PASSWORD:
  #      GATEWAY_PORT:
  #      GATEWAY_PROFILES:
  #      NEXT_URL:
  #      IP_ADDRESS:

  microservices-account:
    container_name: microservices-account
    build:
      context: ./microservices-account
      dockerfile: Dockerfile
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env

  microservices-uno:
    container_name: microservices-uno
    build:
      context: ./microservices-uno
      dockerfile: Dockerfile
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env

  microservices-home:
    container_name: microservices-home
    build:
      context: ./microservices-home
      dockerfile: Dockerfile
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 500m
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - microservices-registry
      - microservices-configuration
    env_file:
      - .env
