server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:192.168.1.254}:${REGISTRY_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: ${REGION:local}
  instance:
    appname: account
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    metadata-map:
      version: ${VERSION:dev}
      region: ${REGION:local}

spring:
  datasource:
    url: jdbc:mysql://mysql.rds.aliyuncs.com:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: ${REDIS_HOST:192.168.1.254}
    password: ${REDIS_PASSWORD:test}
    port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO