### 登录
POST http://{{host}}/ACCOUNT/login
Accept: application/json
Content-Type: application/json

{
  "username": "sbx0",
  "password": "test"
}

> {%
client.global.set("tokenName", response.body.tokenName);
client.global.set("tokenValue", response.body.tokenValue);
%}

### 注册
POST http://{{host}}:8080/ACCOUNT/register
satoken: {{tokenValue}}
Accept: application/json
Content-Type: application/json

{
  "username": "sbx00",
  "password": "test"
}

### 测试
GET http://{{host}}:8080/ACCOUNT/user/loginInfo
satoken: {{tokenValue}}
Accept: application/json
Content-Type: application/json