server:
  port: ${ACCOUNT_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.245.239:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: ${REGION:local}
    registryFetchIntervalSeconds: 5
  instance:
    ip-address: 172.26.245.239
    appname: account
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    metadata-map:
      version: online
      region: server

spring:
  application:
    name: account
  datasource:
    url: ${DB_URL:jdbc:mysql://test/tset?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: ${REDIS_HOST:test}
    password: ${REDIS_PASSWORD:test}
    port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ./logs/account.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/account-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: false
      max-file-size: 1MB
      total-size-cap: 1GB
      max-history: 30
  level:
    root: info

sa-token:
  token-name: token
