server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://192.168.1.254:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: ${REGION:local}
    registryFetchIntervalSeconds: 5
  instance:
    ip-address: 172.26.245.239
    appname: gateway
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    metadata-map:
      version: ${VERSION:dev}
      region: ${REGION:local}

spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.1\.(.*)
    loadbalancer:
      cache:
        enable: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
        httpclient:
          connect-timeout: 1000
          response-timeout: 5s
      routes:
        - id: nextjs
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**
  redis:
    database: 0
    host: ${REDIS_HOST:192.168.1.254}
    password: ${REDIS_PASSWORD:test}
    port: ${REDIS_PORT:6379}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

logging:
  level:
    root: INFO

sa-token:
  token-name: token
