server:
  port: ${PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://192.168.1.254:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: ${REGION:local}
  instance:
    appname: configuration
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    metadata-map:
      version: ${VERSION:dev}
      region: ${REGION:local}

spring:
  application:
    name: configuration
  cloud:
    inetutils:
      preferred-networks: 192.168.1\.(.*)
    config:
      server:
        native:
          search-locations: ${CONFIG_LOCATION:file:C:\Users\JsonSnow\IdeaProjects\microservices\microservices-configuration\src\main\resources\configurations}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: configuration
    port: ${PORT:8888}

logging:
  level:
    - root: info