server:
  port: ${CONFIGURATION_PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL:https://192.168.1.254:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: ${REGION:local}
  instance:
    ip-address: ${IP_ADDRESS:172.30.40.220}
    appname: configuration
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    metadata-map:
      version: ${VERSION:dev}
      region: ${REGION:local}

spring:
  application:
    name: configuration
  cloud:
    inetutils:
      preferred-networks: 192.168.1\.(.*)
    config:
      server:
        native:
          search-locations: file:${CONFIG_LOCATION:C:\Users\winmj\IdeaProjects\microservices\microservices-configuration\src\main\resources\configurations}
  security:
    user:
      name: ${SECURITY_NAME:sbx0}
      password: ${SECURITY_PASSWORD:123456}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: configuration
    port: ${CONFIGURATION_PORT:8888}

logging:
  level:
    - root: info