name: Code Coverage Workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Generate test coverage report
        run: mvn clean verify
      - name: export CODACY_PROJECT_TOKEN
        run: export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Upload
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
