name: Build Workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: codacy-code-coverage

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -DskipTests clean package
      - name: Generate Test Coverage Report
        if: github.ref == 'refs/heads/master'
        run: mvn verify --fail-fast
      - name: Upload Report
        if: github.ref == 'refs/heads/master'
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Upload Report to Server
        if: github.ref == 'refs/heads/master'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.3
        with:
          username: 'root'
          server: '${{ secrets.SSH_IP }}'
          ssh_private_key: ${{ secrets.SSH_TOKEN }}
          local_path: './code-coverage/target/site/jacoco-aggregate/*'
          remote_path: '/root/static/jacoco-aggregate'
          args: '-o ConnectTimeout=5'
